### ISSUE TITLE
special chars in response

### ISSUE THREAD

**Issue by goals2008** [mint-labs/mintlabs#17]
Special chars are returned in projects/subjects list

account.projects-->
[{'id': 97.0, 'name': u'Default Project'},
 {'id': 98.0, 'name': u'BrainData-Test'},
 {'id': 112.0, 'name': u'NE Glioma'}]

project.subjects-->
[u'name', u'Subj3147']

**Comment by alvaroabascar** [comment]
goals2008, what do you refer to as "special chars"?

**Comment by goals2008** [comment]
u infront of the param values that are returned

**Comment by alvaroabascar** [comment]
When parsing the responses from the server we are using json.loads(), and strings are retrieved as unicode strings, that's why they appear as u'string'.

I might be wrong, but this should not be a problem.
