### ISSUE TITLE
500 Error when calling start_analysis

### ISSUE THREAD

**Issue by goals2008** [mint-labs/mintlabs#18]
Need documentation for start_analysis. What should be the container id that need to be passed.
Currently getting following error, if dummy container id is passed

:

b3147.start_analysis('volumetry',112)
ERROR:root:Server returned status 500.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-33-fbc265c899c6> in <module>()
----> 1 b3147.start_analysis('volumetry',112)

//anaconda/lib/python2.7/site-packages/mintlabs/Subject.pyc in start_analysis(self, script_name, in_container_id)
    240         post_data = {"name": self._name, "script_name": script_name, "in_container_id": in_container_id}
    241         response = self.project._account.send_request("project_manager/project_registration",
--> 242                                                        req_parameters=post_data)
    243 
    244         if response.get("success", False):

//anaconda/lib/python2.7/site-packages/mintlabs/Account.pyc in send_request(self, path, req_parameters, req_headers, stream, return_raw_response)
    194             error = "Server returned status 500."
    195             logging.error(error)
--> 196             raise Exception(error)
    197 
    198         # raise exception if there is no response from server

Exception: Server returned status 500.

**Comment by alvaroabascar** [comment]
I've included a section in the [tutorial](https://mintapi.readthedocs.org/en/latest/tutorial.html) for start_analysis.

However, this needs more testing because I haven't been able to start an analysis yet.

**Comment by alvaroabascar** [comment]
as far as I've tested it's working. at least with "morphology_new"
