### ISSUE TITLE
error starting morphology new

### ISSUE THREAD

**Issue by khamael** [mint-labs/mintlabs#20]
I am trying to run morphology_new but getting following error. I cheked earlier that Server was down for maintenance, but now I am able to access Mintlabs account from browser but still having this issue when running with API.

ERROR:root:Server returned status 500.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-4-a37a1f7e68d4> in <module>()
----> 1 b3147.start_analysis('morphology_new',112)

**Comment by merqurio** [comment]
I'll check it, It's possible that the error was [here](https://github.com/mint-labs/mintlabs/commit/4bf8b2e25dee594d03ec5aec3023c840033964ef)

**Comment by merqurio** [comment]
The code looks correct if the subject `b3147`already exists :+1:
