### ISSUE TITLE
Project activation independent from web

### ISSUE THREAD

**Issue by takayuki-sato** [mint-labs/mintlabs#22]
This is what happened to me.
1. Start uploading many data to 'Project A' from API
2. Visit the platform by a browser and activate 'Project B' while keep uploading data through API
3. The data through API was stored in 'Project B'

The project activation of API should be independent from that of a web browser.

**Comment by merqurio** [comment]
For that, the API should be modified :grin:

**Comment by alvaroabascar** [comment]
To implement this through the API we should check what project is activated before doing each request, and reactivating the project if it has been deactivated through the web. The problem is that this would make things much slower.
