### ISSUE TITLE
Implement optional cache

### ISSUE THREAD

**Issue by alvaroabascar** [mint-labs/mintlabs#25]
Using the API can be a bit slow, partly because it doesn't save the results of the web requests. This should be this way, as the same call to the web might return a different result. However, for some things it might be interesting to have an option (cache=True), such that the last results are retrieved without doing the http request.

This can be solved with a generator.

```python
cache = {}

def optional_cache(function):
    def new_function(*args, use_cache=False, **kwargs):
         # this is the key for the cache
         entry = "{}:{}:{}".format(function.__name__, args, kwargs)
         # if we want to use the cache and it already exists...
         if use_cache and cache[entry]:
                 result = cache[entry]
         else:
                 result = function(*ags, **kwargs)
                 cache[entry] = result
        return result
    return new_function
```

**Comment by merqurio** [comment]
:+1:
