### ISSUE TITLE
Nicely print subjects.

### ISSUE THREAD

**Issue by alvaroabascar** [mint-labs/mintlabs#26]
```python
s = project.get_subject("khamael")
print(s)
```
the output will be:

```<mintlabs.Subject.Subject object at 0x7fdf640a85c0>```

But it would be nice to have at least the name of the subject:

```<mintlabs.Subject.Subject 'khamael' object at 0x7fdf640a85c0>```

**Comment by khamael** [comment]
?

**Comment by alvaroabascar** [comment]
```python
s = project.get_subject("khamael")
print(s)
```
the output will be:

```<mintlabs.Subject.Subject object at 0x7fdf640a85c0>```

But it would be nice to have at least the name of the subject:

```<mintlabs.Subject.Subject 'khamael' object at 0x7fdf640a85c0>```
