### ISSUE TITLE
retrieve Project error

### ISSUE THREAD

**Issue by goals2008** [mint-labs/mintlabs#28]
Getting Name error when using API to retrieve existing project

>>> account.projects
[{'name': u'BrainData-Test', 'id': 98.0}, {'name': u'PresurgDataAnalysis', 'id': 174.0}, {'name': u'ND Presurg', 'id': 231.0}]

>>> **project=Project(account,231)**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**NameError: name 'Project' is not defined**

**Comment by alvaroabascar** [comment]
Hello @goals2008. I see you're following our tutorial, and I've just realized we have a "bug" at that point.

Since you did ```import mintlabs```, then you should do ```project = mintlabs.Project(...)```, instead of ```project = Project(...)```.

I'll correct the tutorial right away. Thank you for posting the issue.

**Comment by goals2008** [comment]
Thank you
